### ISSUE TITLE
请问如何配置服务端数据库

### ISSUE THREAD

**Issue by halley-eng** [vczero/OurTimes#1]
最近在学习nodejs   非常高兴找到你这个项目，研究下，多谢，但是我不知道如何配置服务器数据库
特别是下面这句话：
所有服务和数据需要自己创建，在创建数据库的时候，给定一个管理员用户，管理员用户的tag为{tag:'admin'}

如能详细解释下  将感激不尽

**Comment by vczero** [comment]
好的，明天，我把配置过程写上去。祝好！

发自我的 iPhone

**Comment by halley-eng** [comment]
恩恩  期待  祝好

**Comment by vczero** [comment]
刚才把配置写成md文件了，可以看这个：https://github.com/vczero/OurTimes/tree/master/%E9%85%8D%E7%BD%AE%E7%9B%B8%E5%85%B3

**Comment by halley-eng** [comment]
恩   按照您说的步骤已经搞定了  多谢

**Comment by vczero** [comment]
哈，客气了
